version: "3"

services:
  wppconnect:
    container_name: wpp-server-advicerksa
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21460:21460"

volumes:
  wppconnect_tokens: {}      
